### ISSUE TITLE
Add export to plain/text preview

### ISSUE THREAD

**Issue by ejilay** [ejilay/draftjs#6]
- cycle on blocks and join texts with separator (`\n`)
or 
- make it possible through #8 (export to not only HTML)

**Comment by nicksrandall** [comment]
I'm in need of this feature for a product that I am working on and I would love to help. Are you open to accepting PRs? Do you have any direction for me before I get started?

**Comment by ejilay** [comment]
@nicksrandall I'll do this in few hours)

**Comment by ejilay** [comment]
@nicksrandall oh, sorry! I was in a hurry yesterday and have not read all the message from you! This small project need a hero like you) And I will be very happy to see first collab Pull Request. Or I will make this patch soon if you don't) 

It could be something as simple as this:
```go
        emptyConfig := &draftjs.Config{}
	for _, content := range contentBlocks {
		buffer.WriteString(draftjs.Render(content, emptyConfig))
		buffer.WriteString("\n")
	}
```

**Comment by juniperalcorn** [comment]
Hello! This would still be a helpful feature for me, and I see there is work on this. What would it take to finish the work/get to a PR? I'd be happy to help if I can.

**Comment by ejilay** [comment]
> Hello! This would still be a helpful feature for me, and I see there is work on this. What would it take to finish the work/get to a PR? I'd be happy to help if I can.

Hello! Ive just updated the repo and need help in improving tests. They are absolutely awful and now is incorrect because of not precise merge and rebase by me. Code is now mostly working I guess, but it need to be tested. You can help with good testing rewrite if you would like to. You are welcome. 

Can I help you somehow?

**Comment by juniperalcorn** [comment]
@ejilay I'll get started on it in the next few days and let you know if I have questions!

**Comment by ejilay** [comment]
@juniperalcorn I found some time and finished that. have a good luck :)

**Comment by juniperalcorn** [comment]
thank you @ejilay , sorry I couldn't get to it quicker.
